function y = CorrelationLengthWeightedAVGInfo(SumOfWeightedCorrLengths, ...
	SumOfCorrLengthWeights, CorrLengthWeightedAVGError)
   
    CorrLengthWeightedAVG = SumOfWeightedCorrLengths / ...
		SumOfCorrLengthWeights;
    CorrLengthWeightedAVGError = ceil(CorrLengthWeightedAVGError ...
		/10^floor(log10(CorrLengthWeightedAVGError))) ...
			*10^floor(log10(CorrLengthWeightedAVGError)); % salt to suit... 
    CorrLengthErrorInfoAVG = num2str(CorrLengthWeightedAVGError);
    CorrLengthErrorInfoAVG = cat(2,'(',CorrLengthErrorInfoAVG,')');
    CorrLengthWeightedAVG = num2str(CorrLengthWeightedAVG);
    CorrLengthWeightedAVG = CorrLengthWeightedAVG(1:end-4);
    y = 'Correlation Length: ';
    y = cat(2, y, CorrLengthWeightedAVG,' ', CorrLengthErrorInfoAVG,' [A]'); 